name: "macOS"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  macos-11:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Install dependencies 🔧
        run: brew install imagemagick jhead

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Get assert.sh 🎁
        run: curl -f "https://raw.githubusercontent.com/lehmannro/assert.sh/v1.1/assert.sh" -o assert.sh

      - name: Test 🛠️
        run: bash test.sh